/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-09-29 06:35:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class adminscreen_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Downloads/eclipse/springbootworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/StudentManagementSystem/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664433678000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1718769574761L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.\r\n");
      out.write("min.css\" rel=\"stylesheet\" integrity=\"sha384-\r\n");
      out.write("T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwy\r\n");
      out.write("kc2MPK8M2HN\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(" .enroll{\r\n");
      out.write(" background-image: url(\"images/computer.jpeg\");\r\n");
      out.write(" background-size: cover;\r\n");
      out.write(" background-repeat: no-repeat;\r\n");
      out.write(" }\r\n");
      out.write(" .heading{\r\n");
      out.write(" font-family:cursive;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" margin-bottom: 20px;\r\n");
      out.write(" }\r\n");
      out.write(" form{\r\n");
      out.write(" width:400px\r\n");
      out.write(" }\r\n");
      out.write(" .view{\r\n");
      out.write(" background-image: url(\"images/black.jpeg\");\r\n");
      out.write(" background-size: cover;\r\n");
      out.write(" background-repeat: no-repeat;\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function fees()\r\n");
      out.write(" {\r\n");
      out.write(" document.fn.action=\"/fees\"\r\n");
      out.write(" document.action.submit();\r\n");
      out.write(" }\r\n");
      out.write(" function batch()\r\n");
      out.write(" {\r\n");
      out.write(" document.fn.action=\"/batch\"\r\n");
      out.write(" document.action.submit();\r\n");
      out.write(" }\r\n");
      out.write(" function remove()\r\n");
      out.write(" {\r\n");
      out.write(" document.fn.action=\"/remove\"\r\n");
      out.write(" document.action.submit();\r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"d-flex justify-content-between p-2 border border-primary\" >\r\n");
      out.write("<img src=\"images/CJClogo.png\" width=\"100px\" height=\"50px\">\r\n");
      out.write("<div class=\"pt-2\">\r\n");
      out.write("<a href=\"#enroll\">\r\n");
      out.write(" <button class=\"btn btn-outline-primary\">Enroll Student</button>\r\n");
      out.write("</a>\r\n");
      out.write("<a href=\"#view\">\r\n");
      out.write(" <button class=\"btn btn-outline-primary\">View Student</button>\r\n");
      out.write("</a>\r\n");
      out.write("<a href=\"/\">\r\n");
      out.write(" <button class=\"btn btn-outline-primary\">Logout</button>\r\n");
      out.write("</a>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<section class=\"vh-100 gradient-custom enroll mt-2\" id=\"enroll\">\r\n");
      out.write(" <div class=\"container h-100\">\r\n");
      out.write(" <div class=\"row justify-content-center h-100 w-75\">\r\n");
      out.write(" <div class=\"col-12 col-lg-9 col-xl-7\">\r\n");
      out.write(" <div class=\"card shadow-2-strong card-registration mt-0\" style=\"border-radius: 15px;\">\r\n");
      out.write(" <div class=\"card-body mt-0\">\r\n");
      out.write(" <h3 class=\"heading\">Student Enrollment Form</h3>\r\n");
      out.write("\r\n");
      out.write(" <form action=\"enroll_student\">\r\n");
      out.write("\r\n");
      out.write(" <div class=\"row \" >\r\n");
      out.write(" <div class=\"col-md-6 mb-2\">\r\n");
      out.write(" <div class=\"form-outline\">\r\n");
      out.write(" <input type=\"text\" id=\"firstName\" class=\"form-control form-control-sm\" name=\"studentFullName\"/>\r\n");
      out.write(" \r\n");
      out.write(" <label class=\"form-label\" for=\"firstName\">First Full Name</label>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"col-md-6 mb-2\">\r\n");
      out.write(" <div class=\"form-outline\">\r\n");
      out.write(" <input type=\"email\" id=\"lastName\" class=\"form-control form-control-sm\" name=\"studentEmail\"/>\r\n");
      out.write(" <label class=\"form-label\" for=\"lastName\">Student Email</label>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write(" <div class=\"col-md-6 mb-2 d-flex align-items-center\">\r\n");
      out.write(" <div class=\"form-outline datepicker w-100\">\r\n");
      out.write(" <input type=\"number\" class=\"form-control form-control-sm\" id=\"birthdayDate\" name=\"StudentAge\"/>\r\n");
      out.write(" <label for=\"birthdayDate\" class=\"form-label\">Student Age</label>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"col-md-6 mb-2 pb-2\">\r\n");
      out.write(" <div class=\"form-outline\">\r\n");
      out.write(" <input type=\"tel\" id=\"text\" class=\"form-control form-control-sm\" name=\"studentCollageName\"/>\r\n");
      out.write(" <label class=\"form-label\" for=\"phoneNumber\">Student Collage Name</label>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write(" <div class=\"col-md-6 mb-2 pb-2\">\r\n");
      out.write(" <div class=\"form-outline\">\r\n");
      out.write(" <input type=\"number\" id=\"emailAddress\" class=\"form-control form-control-sm\" name=\"feesPaid\"/>\r\n");
      out.write(" <label class=\"form-label\" for=\"emailAddress\">Fees Paid</label>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"col-md-6 mb-2\">\r\n");
      out.write(" <h6 class=\"mb-2 pb-1\">Student Course : </h6>\r\n");
      out.write(" <div class=\"form-check form-check-inline\">\r\n");
      out.write(" <input class=\"form-check-input\" type=\"radio\" name=\"StudentCourse\" id=\"java\" value=\"Java\"\r\n");
      out.write("checked />\r\n");
      out.write(" <label class=\"form-check-label\" for=\"java\">Java</label>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"form-check form-check-inline\">\r\n");
      out.write(" <input class=\"form-check-input\" type=\"radio\" name=\"StudentCourse\" id=\"python\" value=\"Python\" />\r\n");
      out.write(" <label class=\"form-check-label\" for=\"python\">Python</label>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"form-check form-check-inline\">\r\n");
      out.write("<input class=\"form-check-input\" type=\"radio\" name=\"StudentCourse\" id=\"testing\" value=\"Testing\"\r\n");
      out.write("/>\r\n");
      out.write(" <label class=\"form-check-label\" for=\"testing\">Testing</label>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write(" <div class=\"col\">\r\n");
      out.write(" <select class=\"select form-control-sm\" name=\"batchMode\">\r\n");
      out.write(" <option value=\"#\" disabled >Select Batch Mode</option>\r\n");
      out.write(" <option value=\"Online\">Online</option>\r\n");
      out.write(" <option value=\"Offline\">Offline</option>\r\n");
      out.write("\r\n");
      out.write(" </select>\r\n");
      out.write("<label class=\"form-label select-label\">Batch Mode</label>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"col\">\r\n");
      out.write(" <select class=\"select form-control-sm\" name=\"batchNumber\">\r\n");
      out.write(" <option value=\"#\" disabled>Select Batch Number</option>\r\n");
      out.write(" <option value=\"FDJ-160\">FDJ-160</option>\r\n");
      out.write(" <option value=\"REG-160\">REG-160</option>\r\n");
      out.write(" <option value=\"FDJ-161\">FDJ-161</option>\r\n");
      out.write(" <option value=\"REG-161\">REG-162</option>\r\n");
      out.write("<option value=\"FDJ-162\">FDJ-162</option>\r\n");
      out.write(" <option value=\"REG-162\">REG-162</option>\r\n");
      out.write(" <option value=\"FDJ-163\">FDJ-163</option>\r\n");
      out.write(" <option value=\"REG-163\">REG-163</option>\r\n");
      out.write(" <option value=\"FDJ-164\">FDJ-164</option>\r\n");
      out.write(" <option value=\"REG-164\">REG-164</option>\r\n");
      out.write(" <option value=\"FDJ-165\">FDJ-165</option>\r\n");
      out.write(" <option value=\"REG-165\">REG-165</option>\r\n");
      out.write(" </select>\r\n");
      out.write("<label class=\"form-label select-label\">Batch Number</label>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"mt-2 pt-2 d-flex justify-content-center\">\r\n");
      out.write(" \r\n");
      out.write(" <input class=\"btn btn-primary btn-lg\" type=\"submit\" value=\"Submit\" />\r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" </form>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<section class=\"view\" style=\"height:530px\" id=\"view\">\r\n");
      out.write("<h1>View Student</h1>\r\n");
      out.write("<div class=\"text-center w-100\">\r\n");
      out.write(" \r\n");
      out.write(" <form action=\"search\" class=\"w-100\">\r\n");
      out.write(" \r\n");
      out.write(" <select class=\"select form-control-sm border border-primary\"\r\n");
      out.write("name=\"batchNumber\">\r\n");
      out.write(" \r\n");
      out.write(" <option value=\"#\" slected>Select Batch Number</option>\r\n");
      out.write(" <option value=\"FDJ-160\">FDJ-160</option>\r\n");
      out.write(" <option value=\"REG-160\">REG-160</option>\r\n");
      out.write(" <option value=\"FDJ-161\">FDJ-161</option>\r\n");
      out.write(" <option value=\"REG-161\">REG-161</option>\r\n");
      out.write(" <option value=\"FDJ-162\">FDJ-162</option>\r\n");
      out.write(" <option value=\"REG-162\">REG-162</option>\r\n");
      out.write(" <option value=\"FDJ-163\">FDJ-163</option>\r\n");
      out.write(" <option value=\"REG-163\">REG-163</option>\r\n");
      out.write(" <option value=\"FDJ-164\">FDJ-164</option>\r\n");
      out.write(" <option value=\"REG-164\">REG-164</option>\r\n");
      out.write(" <option value=\"FDJ-165\">FDJ-165</option>\r\n");
      out.write(" <option value=\"REG-165\">REG-165</option>\r\n");
      out.write(" </select>\r\n");
      out.write(" <button class=\"btn btn-outline-primary mb-1\">Search</button>\r\n");
      out.write(" </form>\r\n");
      out.write(" \r\n");
      out.write(" <marquee>\r\n");
      out.write(" <h1 style=\"color: red;\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </h1>\r\n");
      out.write(" </marquee>\r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write(" <form name=\"fn\">\r\n");
      out.write(" <table class=\"table table-hover\" style=\"font-size:small\">\r\n");
      out.write("  <thead>\r\n");
      out.write("  <tr>\r\n");
      out.write(" <th>Student ID</th>\r\n");
      out.write(" <th>Student Name</th>\r\n");
      out.write(" <th>Student Email</th>\r\n");
      out.write(" <th>Student Age</th>\r\n");
      out.write(" <th>Collage Name</th>\r\n");
      out.write(" <th>Course Name</th>\r\n");
      out.write(" <th>Batch No</th>\r\n");
      out.write(" <th>Batch Mode</th>\r\n");
      out.write(" <th>Fess Recived</th>\r\n");
      out.write(" <th>select</th>\r\n");
      out.write(" <th>Actions</th>\r\n");
      out.write(" </tr>\r\n");
      out.write(" </thead>\r\n");
      out.write(" <tbody>\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" </tbody>\r\n");
      out.write(" </table>\r\n");
      out.write(" </form>\r\n");
      out.write("</section>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /view/adminscreen.jsp(232,1) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/view/adminscreen.jsp(232,1) '${data}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${data}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /view/adminscreen.jsp(232,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("s");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write(" <tr>\r\n");
            out.write(" <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.studentid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.studentFullName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.studentEmail}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.studentAge}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.studentCollageName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.studentCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.batchNumber}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.batchMode}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.feesPaid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" <td>\r\n");
            out.write(" <input type=\"radio\" name=\"id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.studentid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write(" </td>\r\n");
            out.write(" <td>\r\n");
            out.write(" <div class=\"btn-group btn-group-sm\" role=\"group\" aria-label=\"...\">\r\n");
            out.write(" <button class=\"btn btn-outline-success\" onClick=\"fees()\">Pay-Fees</button>\r\n");
            out.write(" <button class=\"btn btn-outline-primary\" onClick=\"batch()\">Shift-Batch</button>\r\n");
            out.write(" <button class=\"btn btn-outline-danger\" onClick=\"remove()\">Remove</button>\r\n");
            out.write(" </div>\r\n");
            out.write("\r\n");
            out.write(" </td>\r\n");
            out.write(" </tr>\r\n");
            out.write(" ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
